spring:
  datasource:
    url: jdbc:h2:file:./db # в корне проект файл бд db.mv.db
    username: u # имя пользователя консоли
    password: 1 # пароль консоли
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  liquibase:
    enabled: false
